add Podium.slugGenerator to specify your own slugGenerator
bizley/yii2-podium pull request #106
Opened 2017-04-22 21:07 UTC by davidnewcomb

This is a solution to #102. It's pretty simple and has the most flexibility.

**main.php**
```
'modules' => [
	'podium' => [
		'class' => 'bizley\podium\Podium',
		'slugGenerator' => MyPodiumSlugGenerator::className(),
	],
```

**MyPodiumSlugGenerator.php**
```
<?php
namespace common\components;

use bizley\podium\slugs\PodiumSluggableBehavior;

class PodiumSlugGenerator extends PodiumSluggableBehavior {

	protected function generateSlug($slugParts) {
		if ($this->type == self::THREAD) {
			$s = substr($slugParts[0], 1);
			return str_replace("/", "-", $s);
		} else {
			return parent::generateSlug ( $slugParts );
		}
	}
}
```

2017-04-22 21:09 UTC, davidnewcomb commented
In the places that expect a version I have just put x.x because I don't know the final version.

2017-04-23 09:07 UTC, bizley requested changes

2017-04-23 09:07 UTC, bizley commented on src/Podium.php
> +     * @var slugGenerator Name of implementation of PodiumSluggableBehavior.
/**
     * @var string Qualified name of class responsible for generating Podium slugs.
     * You can implement your own generator by extending bizley\podium\slugs\PodiumSluggableBehavior - 
     * see this class for details.
     * @since 0.8
     */

2017-04-23 09:07 UTC, bizley commented on src/Podium.php
> +    public $slugGenerator = false;
public $slugGenerator;

It's easier to leave it as `null` by default.

2017-04-23 09:07 UTC, bizley commented on src/Podium.php
> +        if (!is_string($this->slugGenerator) || $this->slugGenerator != '') {
if (!is_string($this->slugGenerator)) {

Put this inside `if (Yii::$app instanceof WebApplication)` condition.

2017-04-23 09:07 UTC, bizley commented on src/slugs/PodiumSluggableBehavior.php
> + * Slug generator model
* Slug generator behavior

2017-04-23 09:07 UTC, bizley commented on src/slugs/PodiumSluggableBehavior.php
> + *
Example would be nice ;)

2017-04-23 09:07 UTC, bizley commented on src/slugs/PodiumSluggableBehavior.php
> + * @since x.x
* @since 0.8

2017-04-23 09:07 UTC, bizley commented on src/slugs/PodiumSluggableBehavior.php
> +
No empty line here.

2017-04-23 09:07 UTC, bizley commented on src/slugs/PodiumSluggableBehavior.php
> +class PodiumSluggableBehavior extends SluggableBehavior {
Code style: brace on the line underneath the class name.

2017-04-23 14:24 UTC, merged

2017-04-23 14:24 UTC, bizley commented
Cheers!