Console improvements
bizley/yii2-podium pull request #73
Opened 2016-12-22 01:09 UTC by pavlm

1. QueueController now uses Podium module db connection by default, and not application 'db' component
2. console UserController added, with assign and revoke role actions (RBAC cli)

2016-12-22 08:24 UTC, bizley requested changes
Some changes are required.

2016-12-22 08:24 UTC, bizley commented on src/Podium.php
> -        if (Yii::$app instanceof WebApplication) {
There is no point of overloading the console components. Now only `db` is needed and since for Web it is taken directly from configuration there is no point of doing this through Podium. With your changes you basically need `db`, `rbac` and `cache` and I would extract them in something like `$this->podiumComponent->registerConsoleComponents();`.

2016-12-22 08:24 UTC, bizley commented on src/console/QueueController.php
> +                    ->count('*', $this->db);
Since we are doing this let's make it `->count('id', $this->db)`

2016-12-22 08:24 UTC, bizley commented on src/console/QueueController.php
> +                    ->count('*', $this->db);
`*` -> `id`

2016-12-22 08:24 UTC, bizley commented on src/console/QueueController.php
> +                    ->count('*', $this->db);
`*` -> `id`

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> + * RBAC cli
More user friendly description needed here.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +    /**
Method description needed.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +     * @param integer|string $idOrEmail
`integer` -> `int` to make it consistent with the rest of Podium.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +        if (!$user = is_numeric($idOrEmail) ? User::findOne($idOrEmail) : User::findOne(['email' => $idOrEmail])) {
The same block is used 3 times, would be good to extract it.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +     * @param integer|string $idOrEmail
It would be good to mention that user ID is not inherited user ID in case of such configuration.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +     * @param integer|string $idOrEmail
`integer` -> `int`

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +     * @param integer|string $idOrEmail
`integer` -> `int`

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +    /**
Method description needed.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +    /**
Method description needed.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +        $rbac->assign($role, $user->id);
Podium uses single role per user now so if there is another role already assigned it needs to be revoked first.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +        if (!$user = is_numeric($idOrEmail) ? User::findOne($idOrEmail) : User::findOne(['email' => $idOrEmail])) {
Please use `find()->limit(1)->one()` for consistency.

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +            $this->stderr('no user found' . PHP_EOL);
`no user found` -> `User not found.`

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +            return 1;
`1` -> `self::EXIT_CODE_ERROR`

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +            $this->stderr('no such role' . PHP_EOL);
`no such role` -> `No such role.`

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +            return 1;
`1` -> `self::EXIT_CODE_ERROR`

2016-12-22 08:24 UTC, bizley commented on src/console/UserController.php
> +        $rbac->revoke($role, $user->id);
At least one role must be assigned (default is `Rbac::ROLE_USER`).

2016-12-23 00:06 UTC, pavlm commented
Refactored.

2016-12-23 07:56 UTC, bizley requested changes
Just 2 more things and it's perfect. Cheers!

2016-12-23 07:56 UTC, bizley commented on src/console/UserController.php
> +        $rbac->revoke($role, $user->id);
In case of revoking Podium role you need to check if at least `Rbac::ROLE_USER` is assigned.

2016-12-23 07:56 UTC, bizley commented on src/console/UserController.php
> +     */
Add `@return User`

2016-12-23 18:24 UTC, bizley approved these changes
Thank you!

2016-12-23 18:24 UTC, merged